Introduce a new experimental way to submit by using the Merge API. (#85)

diff --git a/bin/git-submit b/bin/git-submit
--- a/bin/git-submit
+++ b/bin/git-submit
@@ -21,23 +21,26 @@ else
   FORCE_SUBMIT="$2"
 fi
 if [ -z "${BRANCH}" ]; then
-	BRANCH="$(git rev-parse --abbrev-ref HEAD)"
-	if [ "${BRANCH}" == "master" ]; then
-		echo "branch required:" 1>&2
-		git branch | grep -v \ master$ 1>&2
-		exit 1
-	fi
+  BRANCH="$(git rev-parse --abbrev-ref HEAD)"
+  if [ "${BRANCH}" == "master" ]; then
+    echo "branch required:" 1>&2
+    git branch | grep -v \ master$ 1>&2
+    exit 1
+  fi
 fi
+
+# Enable specific option if user has the experimental GIT_SUBMIT_EXPERIMENTAL env var set.
+readonly SQUASH_ON_GITHUB="${GIT_SUBMIT_EXPERIMENTAL}"
 
 # Ensures that current dir is clean.
 if [ -n "$(git diff HEAD --shortstat 2> /dev/null | tail -n1)" ]; then
-	echo "Current git status is dirty. Commit, stash or revert your changes before submitting." 1>&2
-	exit 2
+  echo "Current git status is dirty. Commit, stash or revert your changes before submitting." 1>&2
+  exit 2
 fi
 
 if ! git rev-parse --verify "${BRANCH}" 2>&1 > /dev/null; then
-	echo "${BRANCH} is not a valid branch." 1>&2
-	exit 8
+  echo "${BRANCH} is not a valid branch." 1>&2
+  exit 8
 fi
 
 # Ensures that the Continuous Integration is successful.
@@ -72,73 +75,127 @@ readonly BRANCH_MERGE="$(git config "branch.${BRANCH}.merge" | sed -e s/^refs\\/
 
 # Abort all changes and restore initial state before exiting.
 function abort {
-	echo "Something went wrong, aborting:" 1>&2
+  echo "Something went wrong, aborting:" 1>&2
 
-	echo "  Set branch master to ${BASE_MASTER}." 1>&2
-	git checkout -f master
-	git reset --hard "${BASE_MASTER}"
+  echo "  Set branch master to ${BASE_MASTER}." 1>&2
+  git checkout -f master
+  git reset --hard "${BASE_MASTER}"
 
-	echo "  Set branch ${BRANCH} to ${BRANCH_INITIAL}." 1>&2
-	git checkout -f "${BRANCH}"
-	git reset --hard "${BRANCH_INITIAL}"
+  echo "  Set branch ${BRANCH} to ${BRANCH_INITIAL}." 1>&2
+  git checkout -f "${BRANCH}"
+  git reset --hard "${BRANCH_INITIAL}"
 
-	exit 7
+  exit 7
 }
 
 # Check that the changes are bundled as one commit on top of origin/master.
 while [ "${BASE_MASTER}" != "$(git rev-parse "${BRANCH}^")" ]; do
-	if [ "${BASE_MASTER}" = "$(git rev-parse "${BRANCH}")" ]; then
-		echo "No changes to submit."
-		exit 3
-	fi
-	if ( git merge-base --is-ancestor "$(git rev-parse "${BRANCH}^")" "${BASE_MASTER}" ); then
-		if ! (git rebase "${BASE_BRANCH}" "${BRANCH}"); then
-			git rebase --abort
-			exit 10
-		fi
-	else
-		echo "You should first group all your changes in one commit:" 1>&2
-		echo "  git rebase -i ${BASE_BRANCH} ${BRANCH}" 1>&2
-		read -p "Rebase now? [y/N]" answer
-		if [ "${answer}" == "y" ] || [ "${answer}" == "Y" ]; then
-			if ! (git rebase -i "${BASE_BRANCH}" "${BRANCH}"); then
-				git rebase --abort
-				exit 9
-			fi
-		else
-			exit 4
-		fi
-	fi
+  if [ "${BASE_MASTER}" == "$(git rev-parse "${BRANCH}")" ]; then
+    echo "No changes to submit."
+    exit 3
+  fi
+  if ( git merge-base --is-ancestor "$(git rev-parse "${BRANCH}^")" "${BASE_MASTER}" ); then
+    # There is only one new commit, but it's based on an old version of master.
+    if [[ -z "${SQUASH_ON_GITHUB}" ]] && ! (git rebase "${BASE_BRANCH}" "${BRANCH}"); then
+      git rebase --abort
+      exit 10
+    fi
+    break
+  else
+    echo "You should first group all your changes in one commit:" 1>&2
+    echo "  git rebase -i ${BASE_BRANCH} ${BRANCH}" 1>&2
+    if [[ -n "${SQUASH_ON_GITHUB}" ]]; then
+      exit 12
+    fi
+    read -p "Rebase now? [y/N]" answer
+    if [ "${answer}" == "y" ] || [ "${answer}" == "Y" ]; then
+      if ! (git rebase -i "${BASE_BRANCH}" "${BRANCH}"); then
+        git rebase --abort
+        exit 9
+      fi
+    else
+      exit 4
+    fi
+  fi
 done
 
 # Check that the branch is tracking a remote branch.
 if [ -z "${BRANCH_REMOTE}" ]; then
-	echo "The branch ${BRANCH} is not tracked and has probably never been reviewed." 1>&2
-	echo "  git push -u ${BASE_REMOTE} ${BRANCH}"
-	read -p "Push now? [y/N]" answer
-	if [ "${answer}" == "y" ] || [ "${answer}" == "Y" ]; then
-		git push -u ${BASE_REMOTE} ${BRANCH} || abort
-	fi
-	exit 5
+  echo "The branch ${BRANCH} is not tracked and has probably never been reviewed." 1>&2
+  echo "  git push -u ${BASE_REMOTE} ${BRANCH}"
+  read -p "Push now? [y/N]" answer
+  if [ "${answer}" == "y" ] || [ "${answer}" == "Y" ]; then
+    git push -u ${BASE_REMOTE} ${BRANCH} || abort
+  fi
+  exit 5
 fi
 
-# Check that the remote branch is synced with the local one.
-if [ "$(git rev-parse "${BRANCH_REMOTE}/${BRANCH_MERGE}")" != "$(git rev-parse "${BRANCH}")" ]; then
-	echo "Push your branch on ${BRANCH_REMOTE}, or you'll have a hard time removing the pull request:" 1>&2
-	echo "  git push -f ${BRANCH_REMOTE} ${BRANCH}:${BRANCH_MERGE}"
-	git push -f "${BRANCH_REMOTE}" "${BRANCH}:${BRANCH_MERGE}" || abort
-fi
+if [ -n "${SQUASH_ON_GITHUB}" ]; then
+  # Get OAuth Token.
+  # We use the hub config located in ~/.config/hub, it's a yaml file with first
+  # level keys being the server domains. And then it has a subkey with
+  # oauth_token:
+  #   github.com
+  #   - user: pcorpet
+  #     oauth_token: 0123456789abcdef
+  #     protocol: https
+  #   entreprise.github.com
+  #   - user: pascal
+  #     oauth_token: abcdef0123456789
+  readonly GITHUB_OAUTH_TOKEN="$(sed -n '/^github.com/,$p' ~/.config/hub | grep oauth_token | head -1 | cut -d: -f2 | sed -e "s/ //")"
+  if [ -z "${GITHUB_OAUTH_TOKEN}" ]; then
+    echo "Could not find OAuth Token to connect to GitHub API." 1>&2
+    abort
+  fi
 
-# Update master locally.
-git checkout master
-if ! (git rebase "${BRANCH}"); then
-	git rebase --abort
-	abort
-fi
+  # Get GitHub repo name.
+  # The remote URL is "git@github.com:bayesimpact/new-project.git" and we want
+  # to extract "bayesimpact" and "new-project".
+  if ! [[ "$(git remote get-url "${BRANCH_REMOTE}")" =~ ^git@github.com:(.*)/(.*).git$ ]]; then
+    echo "Could not find the GitHub repository's name." 1>&2
+    abort
+  fi
+  readonly GITHUB_REPO_USER="${BASH_REMATCH[1]}"
+  readonly GITHUB_REPO_NAME="${BASH_REMATCH[2]}"
 
-# Push updated master to remote.
-git push "${BASE_REMOTE}" master || abort
+  # Find pull-request ID.
+  readonly PULL_REQUEST_NUMBER="$(curl -s \
+    -H "Authorization: token ${GITHUB_OAUTH_TOKEN}" \
+    "https://api.github.com/repos/${GITHUB_REPO_USER}/${GITHUB_REPO_NAME}/pulls?base=master&head=${GITHUB_REPO_USER}:${BRANCH_MERGE}" | \
+    # The result is a large JSON nicely indented with one property per line,
+    # and we search for the "number" property: '  "number": 1234' -> '1234'.
+    grep '"number"' | sed -e "s/^.*: //;s/,//")"
+  if [[ -z "${PULL_REQUEST_NUMBER}" ]]; then
+    echo "Could not find the Pull Request number." 1>&2
+    abort
+  fi
+
+  # Ask GitHub to do the squash and merge!
+  curl -X PUT -H "Authorization: token ${GITHUB_OAUTH_TOKEN}" \
+    "https://api.github.com/repos/${GITHUB_REPO_USER}/${GITHUB_REPO_NAME}/pulls/${PULL_REQUEST_NUMBER}/merge" \
+    --data "{\"merge_method\": \"squash\", \"sha\": \"${BRANCH_INITIAL}\"}" || abort
+else
+  # Check that the remote branch is synced with the local one.
+  if [ "$(git rev-parse "${BRANCH_REMOTE}/${BRANCH_MERGE}")" != "$(git rev-parse "${BRANCH}")" ]; then
+    echo "Push your branch on ${BRANCH_REMOTE}, or you'll have a hard time removing the pull request:" 1>&2
+    echo "  git push -f ${BRANCH_REMOTE} ${BRANCH}:${BRANCH_MERGE}"
+    git push -f "${BRANCH_REMOTE}" "${BRANCH}:${BRANCH_MERGE}" || abort
+  fi
+
+  # Update master locally.
+  git checkout master
+  if ! (git rebase "${BRANCH}"); then
+    git rebase --abort
+    abort
+  fi
+
+  # Push updated master to remote.
+  git push "${BASE_REMOTE}" master || abort
+fi
 
 # Remove branch locally and remotely.
-git branch -d "${BRANCH}"
+if [[ "${BRANCH}" == "$(git rev-parse --abbrev-ref HEAD)" ]]; then
+  git checkout master
+fi
+git branch -D "${BRANCH}"
 git push ${BRANCH_REMOTE} ":${BRANCH_MERGE}"
