[Easy Dev] Limit the number of requests to Github's API in git-submit.

diff --git a/bin/git-submit b/bin/git-submit
--- a/bin/git-submit
+++ b/bin/git-submit
@@ -65,13 +65,12 @@ readonly START_BRANCH="$(git rev-parse --abbrev-ref HEAD)"
 
 # Ask Github to merge this PR once CI is successful.
 function enable_auto_merge {
-  local pull_request_id="$(hub api repos/{owner}/{repo}/pulls/$1 | jq -r .node_id)"
   hub api graphql -f query='
     mutation AutoMerge($pullRequestId: ID!) {
       enablePullRequestAutoMerge(input: {pullRequestId: $pullRequestId, mergeMethod: SQUASH}) {
         pullRequest {autoMergeRequest {enabledAt}}
       }
-    }' -f pullRequestId="$pull_request_id" |
+    }' -f pullRequestId="$1" |
     jq -e '.data.enablePullRequestAutoMerge.pullRequest.autoMergeRequest.enabledAt' > /dev/null
 }
 
@@ -102,18 +101,23 @@ function get_pull_request_number {
   git checkout -q "$BRANCH" && (hub pr show -f %I; git checkout -q -)
 }
 
-function is_auto_mergeable {
-  # TODO(cyrille): Factorize with the actual auto_merge enabling.
-  local pull_request_id="$(hub api repos/{owner}/{repo}/pulls/$(get_pull_request_number) | jq -r .node_id)"
-  hub api graphql -f query='
-    query IsAutoMergeable($pullRequestId: ID!) {
-      node(id: $pullRequestId) {
-        ... on PullRequest {
-          viewerCanEnableAutoMerge
+function get_pr_info {
+  hub api graphql -F query='
+    query IsAutoMergeable($headRefName: String!) {
+      repository(name: "{repo}", owner: "{owner}") {
+        pullRequests(last: 1, headRefName: $headRefName, states: [OPEN]) {
+          nodes {
+            id
+            number
+            viewerCanEnableAutoMerge
+          }
         }
       }
-    }
-    ' -f pullRequestId="$pull_request_id" | jq -e '.data.node.viewerCanEnableAutoMerge' > /dev/null
+    }' -F headRefName="$BRANCH_MERGE" |
+    jq '.data.repository.pullRequests.nodes[0]'
+  readonly PULL_REQUEST_NODE_ID="$(jq -r '.id' <<< "$result")"
+  readonly PULL_REQUEST_NUMBER="$(jq -r '.number' <<< "$result")"
+  jq -e '.viewerCanEnableAutoMerge' <<< "$result" > /dev/null
 }
 # Ensures that the Continuous Integration is successful.
 if [ -n "$CAN_USE_HUB" ]; then
@@ -123,7 +127,9 @@ if [ -n "$CAN_USE_HUB" ]; then
       echo "WARNING: forcing submission despite CI status \"${CI_STATUS}\"."
     else
       echo "Continuous integration is \"${CI_STATUS}\""
-      if ! is_auto_mergeable; then
+      readonly PR_INFO_JSON=$(mktmp -t "XXXXXX.json")
+      get_pr_info > "$PR_INFO_JSON"
+      if ! jq -e '.viewerCanEnableAutoMerge' "$PR_INFO_JSON" > /dev/null; then
         GIT_SUBMIT_AUTO_MERGE=0
       fi
       # TODO(cyrille): Check if auto-merge is already enabled, to avoid asking the question.
@@ -177,6 +183,8 @@ function abort {
     git checkout -f "$START_BRANCH"
   fi
 
+  rm -f "$PR_INFO_JSON"
+
   exit 7
 }
 
@@ -224,16 +232,10 @@ fi
 
 if [ -z "${NO_SQUASH_ON_GITHUB}" ] && [ -n "$CAN_USE_HUB" ] ; then
 
-  # Find pull-request ID.
-  readonly PULL_REQUEST_NUMBER="$(get_pull_request_number)"
-  if [[ -z "${PULL_REQUEST_NUMBER}" ]]; then
-    echo "Could not find the Pull Request number." 1>&2
-    abort
-  fi
-
   # Ask GitHub to do the squash and merge!
   if [[ "$GIT_SUBMIT_AUTO_MERGE" == "1" ]]; then
-    if enable_auto_merge "$PULL_REQUEST_NUMBER" ; then
+    readonly PULL_REQUEST_NODE_ID="$(jq -r '.id' "$PR_INFO_JSON")"
+    if [ -n "$PULL_REQUEST_NODE_ID" ] && enable_auto_merge "$PULL_REQUEST_NODE_ID" ; then
       echo "Your branch will be merged once CI is successful."
     else
       echo "Something went wrong while auto-merging your PR."
@@ -241,9 +243,18 @@ if [ -z "${NO_SQUASH_ON_GITHUB}" ] && [ -n "$CAN_USE_HUB" ] ; then
       abort
     fi
   else
+    # Find pull-request ID.
+    readonly PULL_REQUEST_NUMBER="$(jq -r '.number' "$PR_INFO_JSON")"
+    if [[ -z "${PULL_REQUEST_NUMBER}" ]]; then
+      echo "Could not find the Pull Request number." 1>&2
+      abort
+    fi
+
     hub api -X PUT "/repos/{owner}/{repo}/pulls/${PULL_REQUEST_NUMBER}/merge" \
       -F merge_method=squash -F "sha=$BRANCH_INITIAL" | jq -r '.message' || abort
   fi
+
+  rm "$PR_INFO_JSON"
 
   # Update default branch locally.
   git checkout $DEFAULT_BRANCH
